database_insertion_training_params:
  ASTRA_DB_KEYSPACE: "breast_cancer_detection_training"
  db_name: "breast_cancer_detection"
  table_name: "good_raw_data"
  column_names: {'index_column': 'int',
  'radius1': 'float',
 'texture1': 'float',
 'perimeter1': 'float',
 'area1': 'float',
 'smoothness1': 'float',
 'compactness1': 'float',
 'concavity1': 'float',
 'concave_points1': 'float',
 'symmetry1': 'float',
 'fractal_dimension1': 'float',
 'radius2': 'float',
 'texture2': 'float',
 'perimeter2': 'float',
 'area2': 'float',
 'smoothness2': 'float',
 'compactness2': 'float',
 'concavity2': 'float',
 'concave_points2': 'float',
 'symmetry2': 'float',
 'fractal_dimension2': 'float',
 'radius3': 'float',
 'texture3': 'float',
 'perimeter3': 'float',
 'area3': 'float',
 'smoothness3': 'float',
 'compactness3': 'float',
 'concavity3': 'float',
 'concave_points3': 'float',
 'symmetry3': 'float',
 'fractal_dimension3': 'float',
 'diagnosis': 'varchar'
  }

data_preprocessing_training_params:
  label_column_name: diagnosis
  row_threshold: 5000
  test_size: 0.2

model_training_params:
  cv: 3
  linear_regression_params:
    fit_intercept: [True, False]
  sgd_classifier_params:
    loss: ['hinge', 'log_loss', 'modified_huber']
    alpha: [1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04]
    class_weight: [null, 'balanced', {0: 1, 1: 2, 2: 1}]
  random_forest_classifier_params:
    n_estimators: [100, 150, 200]
    criterion: ['gini', 'entropy']
    max_features: ['sqrt', 'log2', null]
    max_depth: [5, 10, 15, 20]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 10, 20]
    bootstrap: [True, False]

