artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_id: 17
  destination_folder: artifacts/data_ingestion/data
  filename: breast_cancer_wisconsin.csv
  miscellaneous_folder: artifacts/data_ingestion/miscellaneous

data_validation_training:
  root_dir: artifacts/data_validation_training/training_raw_files_validated
  good_raw: artifacts/data_validation_training/training_raw_files_validated/good_raw
  bad_raw: artifacts/data_validation_training/training_raw_files_validated/bad_raw
  filename_regex: breast_cancer_wisconsin.csv
  metadata_filename: metadata.txt
  description_filename: variables.txt
  training_source_dir: artifacts/data_ingestion/data
  number_of_columns: 32

data_transformation_training:
  good_raw: artifacts/data_validation_training/training_raw_files_validated/good_raw
  bad_raw: artifacts/data_validation_training/training_raw_files_validated/bad_raw
  archive_bad_raw: artifacts/data_validation_training/archive_bad_raw
  column_names: ['radius1',
 'texture1',
 'perimeter1',
 'area1',
 'smoothness1',
 'compactness1',
 'concavity1',
 'concave_points1',
 'symmetry1',
 'fractal_dimension1',
 'radius2',
 'texture2',
 'perimeter2',
 'area2',
 'smoothness2',
 'compactness2',
 'concavity2',
 'concave_points2',
 'symmetry2',
 'fractal_dimension2',
 'radius3',
 'texture3',
 'perimeter3',
 'area3',
 'smoothness3',
 'compactness3',
 'concavity3',
 'concave_points3',
 'symmetry3',
 'fractal_dimension3',
 'Diagnosis']

database_operations_training:
  root_dir: artifacts/training_file_from_db
  file_name: inputfile.csv
  good_raw: artifacts/data_validation_training/training_raw_files_validated/good_raw
  bad_raw: artifacts/data_validation_training/training_raw_files_validated/bad_raw

data_preprocessing_training:
  root_dir: artifacts/preprocessed_data
  input_file_path: artifacts/training_file_from_db/inputfile.csv
  correlation_dir: artifacts/preprocessed_data/correlation_matrix
  preprocessed_input_data_dir: artifacts/preprocessed_data/preprocessed_input
  test_set_dir: artifacts/preprocessed_data/test_set

model_training:
  root_dir: artifacts/model_training
  models_dir: artifacts/model_training/models
  path_to_preprocessed_train_X: artifacts/preprocessed_data/preprocessed_input/preprocessed_train_X.csv
  path_to_preprocessed_train_y: artifacts/preprocessed_data/preprocessed_input/preprocessed_train_y.csv
  best_models_dir: artifacts/model_training/best_models
  final_model_dir: artifacts/model_training/final_model

model_evaluation:
  root_dir: artifacts/model_evaluation
  final_model: artifacts/model_training/final_model/final_model.joblib
  test_set_feautres: artifacts/preprocessed_data/test_set/test_set_features.csv
  test_set_label: artifacts/preprocessed_data/test_set/test_set_label.csv
  label_column_name: diagnosis
  columns_with_zero_std_dev_path: artifacts/preprocessed_data/columns_with_zero_std_dev.pkl
  knn_imputer_path: artifacts/preprocessed_data/knn_imputer.pkl
  std_scaler_path: artifacts/preprocessed_data/std_scaler.pkl





